name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 0 */4 * *'
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send API Request to Supabase
        run: |
          curl -f -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/statafel_reservations?select=id&limit=1" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
